version: '2'

services:

  test:
    build: .
    depends_on:
      - chrome
    command: /bin/sh -c "ng test && ng e2e"

  hub:
    image: selenium/hub:3.7.1-argon
    environment:
      - "JAVA_OPTS=-Dselenium.LOGGER.level=WARNING"

  chrome:
    image: selenium/node-chrome:3.7.1
    depends_on:
      - hub
    environment:
        - HUB_PORT_4444_TCP_ADDR=hub
        - HUB_PORT_4444_TCP_PORT=4444
        - "JAVA_OPTS=-Dselenium.LOGGER.level=WARNING"
    volumes:
      - /dev/shm:/dev/shm

