// this file will be generated by the dockerfile.
export const environment = {
  production: false,
  api: "https://ws.spraakbanken.gu.se/ws/strixlabb",
  auth: "https://sp.spraakbanken.gu.se/auth"
};
